version: '3.8'

services:
  db:
    image: postgres:16
    container_name: tech_challenge_db
    environment:
      POSTGRES_DB: tech_challenge
      POSTGRES_USER: techuser
      POSTGRES_PASSWORD: techpass
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techuser -d tech_challenge"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - tech_challenge_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tech_challenge_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Database Configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tech_challenge
      SPRING_DATASOURCE_USERNAME: techuser
      SPRING_DATASOURCE_PASSWORD: techpass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

      # JPA Configuration
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

      # Application Configuration
      SPRING_APPLICATION_NAME: tech-challenge-restaurantes
      SERVER_PORT: 8080

      # Security Configuration - CREDENCIAIS FIXAS
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: admin123

      # Documentation
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
      SPRINGDOC_API_DOCS_PATH: /api-docs

      # JWT Configuration
      JWT_SECRET: TechChallengeFiap-2025-SecretKey-ParaSuaAplicacaoSegura!
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000

      # Authentication Configuration
      AUTH_CLIENT_ID: tech-challenge-client
      AUTH_CLIENT_SECRET: tech-challenge-secret

      # Logging
      LOGGING_LEVEL_COM_TECHCHALLENGE: DEBUG
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: DEBUG

    ports:
      - "8080:8080"
    restart: on-failure
    networks:
      - tech_challenge_network

volumes:
  pgdata:
    driver: local

networks:
  tech_challenge_network:
    driver: bridge
